// Auto-generated by scripts/generate-icons.mjs — do not edit manually
export type { IconProps } from './components/StepBackward';

export { default as StepBackwardIcon } from './components/StepBackward';
