/**
 * After SVGR generates components, this script creates src/icons/index.ts
 * with named exports for all icons.
 *
 * Usage: node scripts/generate-icons.mjs
 */

import { readdirSync, writeFileSync } from 'fs';
import { join, basename, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outDir = join(root, 'src/icons/components');

const files = readdirSync(outDir).filter(
  (f) => f.endsWith('.tsx') && f !== 'index.tsx'
);

// e.g. "step-backward.tsx" → componentName "StepBackward", export name "StepBackwardIcon"
function toComponentName(filename) {
  return basename(filename, '.tsx')
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const lines = [
  '// Auto-generated by scripts/generate-icons.mjs — do not edit manually',
  "export type { IconProps } from './components/StepBackward';",
  '',
];

for (const file of files) {
  const name = toComponentName(file);
  lines.push(`export { default as ${name}Icon } from './components/${basename(file, '.tsx')}';`);
}

lines.push('');
writeFileSync(join(root, 'src/icons/index.ts'), lines.join('\n'));
console.log(`Generated src/icons/index.ts — ${files.length} icon(s)`);
